### ISSUE TITLE
安装不上了是怎么回事呀

### ISSUE THREAD

**Issue by WUST-mengqinyu** [im0qianqian/CodeforcesEduHacking#2]
The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package 'Microsoft .NET Framework 4.6.1 (x86 和 x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 528372
Setting value '528372 {int}' for property 'DotNet461Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet461Full_OSIntegrated'
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full\2052'
Read integer value 528372
Setting value '528372 {int}' for property 'DotNet461FullLangPack_Release'
Reading value 'LCID' of registry key 'HKLM\SYSTEM\CurrentControlSet\Control\MUI\UILanguages\zh-CN'
Read integer value 2052
Setting value '2052 {int}' for property 'DotNet461FullLangPack_OS_LCID'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet461FullLangPack_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.6.1 (x86 和 x64)':
Property: [DotNet461FullLangPack_OSIntegrated] = 1 {int}
Property: [DotNet461FullLangPack_OS_LCID] = 2052 {int}
Property: [DotNet461FullLangPack_Release] = 528372 {int}
Property: [DotNet461Full_OSIntegrated] = 1 {int}
Property: [DotNet461Full_Release] = 528372 {int}
Running checks for command 'DotNetFX461\NDP461-KB3102436-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX461\NDP461-KB3102436-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX461\NDP461-KB3102438-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet461Full_Release' and value '394254': true
Result of checks for command 'DotNetFX461\NDP461-KB3102438-Web.exe' is 'Bypass'
Running checks for command 'DotNetFX461\NDP461-KB3102436-x86-x64-AllOS-CHS.exe'
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet461FullLangPack_Release' and value '394254': true
Result of checks for command 'DotNetFX461\NDP461-KB3102436-x86-x64-AllOS-CHS.exe' is 'Bypass'
Running checks for command 'DotNetFX461\NDP461-KB3102436-x86-x64-AllOS-CHS.exe'
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet461FullLangPack_Release' and value '394254': true
Result of checks for command 'DotNetFX461\NDP461-KB3102436-x86-x64-AllOS-CHS.exe' is 'Bypass'
'Microsoft .NET Framework 4.6.1 (x86 和 x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697191'
Error: 试图下载“http://codeforces-edu-hacking.dreamwings.cn/CodeforcesEduHacking.application”时发生错误。

**Comment by im0qianqian** [comment]
抱歉，ssl 证书到期了没更新，然后出现了一些问题。现在不让 http 跳转 https 了，可以再试试。
